/**
 * Import main-story chapters from the community ORV-Reader repo (structured .txt per chapter).
 * Source: https://github.com/Bittu5134/ORV-Reader (chapters/orv/chap_NNNNN.txt)
 *
 *   npm run ingest:bittu
 *
 * Respects their LICENSE; content is fetched at ingest time only (not stored in git).
 * Optional: ORV_MAX_CHAPTERS=10 for a short test run.
 * Optional: ORV_BITTU_DELAY_MS=120 to slow requests if GitHub throttles.
 * Optional: ORV_BITTU_ILLUSTRATIONS=0 — skip <cover>/<img> → panel URLs (default: on).
 *   Illustrations are resolved from the same repo (website/assets/images/), not generated by AI.
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import {
  bittuIllustrationsEnabled,
  preprocessBittuIllustrationLines,
} from "./bittu-illustrations";
import { normalizeText } from "./ingest-shared";
import { writeNovelChaptersToDb } from "./write-novel-db";
import { encodeWindowBlock } from "../src/lib/rich-segments";

const prisma = new PrismaClient();
const PROJECT_ROOT = process.cwd();

const META_URL =
  "https://raw.githubusercontent.com/Bittu5134/ORV-Reader/main/website/meta/orv_meta.json";

function chapterUrl(index: number): string {
  const n = String(index).padStart(5, "0");
  return `https://raw.githubusercontent.com/Bittu5134/ORV-Reader/main/chapters/orv/chap_${n}.txt`;
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

/** Repo files use a `<title>Ch N: …` line; strip pseudo-tags. */
function unwrapBittuTitleBlock(raw: string): string {
  let t = raw.replace(/^\uFEFF/, "");
  if (/^<title>/i.test(t)) {
    t = t.replace(/^<title>\s*/i, "").replace(/<\/title>/gi, "\n");
  }
  return t;
}

/** Per-line cleanup identical to the old `stripBittuMarkup` body. */
function cleanBittuLine(line: string): string | null {
  const t = line.trim();
  if (!t) return "";
  if (t.startsWith("[[[BITTU_IMG:")) return t;
  if (/^<cover>/i.test(t) || /^<\/cover>/i.test(t) || /^<img>/i.test(t))
    return null;
  if (/^\[\d+\]\s/.test(t)) return null;
  if (/^\*\s*(Official|Unofficial)/i.test(t)) return null;
  if (t === "***") return null;
  if (/^\[[^\]]{0,200}\]\[[^\]]{0,80}\]$/.test(t)) return null;
  let cleaned = line.replace(/\[[^\]]+\]\[[^\]]*\]/g, " ").trim();
  cleaned = cleaned.replace(/<\&>/g, "");
  cleaned = cleaned.replace(/\s+/g, " ").trim();
  return cleaned || "";
}

/**
 * Remove Bittu-specific illustration / footnote lines; keep readable
 * prose. Lines surrounded by a bare `+` pair become one "window"
 * segment (see src/lib/rich-segments.ts for the encoding).
 */
export function stripBittuMarkup(raw: string): string {
  const lines = raw.split(/\r?\n/);
  const out: string[] = [];
  let windowBuf: string[] | null = null;
  for (const line of lines) {
    const t = line.trim();
    if (t === "+") {
      if (windowBuf === null) {
        windowBuf = [];
      } else {
        const encoded = encodeWindowBlock(windowBuf);
        if (encoded) out.push(encoded);
        windowBuf = null;
      }
      continue;
    }
    if (windowBuf !== null) {
      const cleaned = cleanBittuLine(line);
      if (cleaned && cleaned.length > 0) windowBuf.push(cleaned);
      continue;
    }
    const cleaned = cleanBittuLine(line);
    if (cleaned === null) continue;
    out.push(cleaned);
  }
  // Dangling unclosed window: salvage the buffered lines as plain paragraphs.
  if (windowBuf && windowBuf.length > 0) out.push(...windowBuf);
  return out.filter((l, i, a) => !(l === "" && a[i + 1] === "")).join("\n");
}

function parseChapterFile(
  index: number,
  raw: string,
  useIllustrations: boolean,
): {
  num: number;
  title: string;
  body: string;
} | null {
  const text = unwrapBittuTitleBlock(raw).trim();
  if (!text) return null;
  const firstNl = text.indexOf("\n");
  const head = (firstNl === -1 ? text : text.slice(0, firstNl)).trim();
  const m = head.match(/^Ch\s+(\d+)\s*:\s*(.+)$/i);
  if (!m) {
    console.warn(`  chap_${String(index).padStart(5, "0")}: bad header, skipped`);
    return null;
  }
  const num = parseInt(m[1], 10);
  const titlePart = m[2]!.trim();
  let rest = firstNl === -1 ? "" : text.slice(firstNl + 1);
  if (useIllustrations) {
    rest = preprocessBittuIllustrationLines(rest);
  }
  const stripped = stripBittuMarkup(rest);
  const body = normalizeText(
    stripped
      .split(/\n/)
      .map((l) => l.trim())
      .filter(Boolean)
      .join("\n\n"),
  );
  if (body.length < 20) return null;
  return { num, title: titlePart, body };
}

async function main() {
  const delay = parseInt(process.env.ORV_BITTU_DELAY_MS ?? "85", 10);
  const maxRaw = process.env.ORV_MAX_CHAPTERS?.trim();
  const maxChapters = maxRaw ? parseInt(maxRaw, 10) : undefined;

  console.log("Fetching chapter list:", META_URL);
  const metaRes = await fetch(META_URL, {
    headers: { "User-Agent": "orv-reader-ingest/1.0" },
  });
  if (!metaRes.ok) throw new Error(`Meta fetch ${metaRes.status}`);
  const meta = (await metaRes.json()) as { chapters?: number };
  const total = meta.chapters ?? 551;
  const limit = maxChapters && maxChapters > 0 ? Math.min(maxChapters, total) : total;

  const useIll = bittuIllustrationsEnabled();
  console.log(
    `Downloading ${limit} chapter file(s) from Bittu5134/ORV-Reader (delay ${delay}ms)${
      useIll ? ", with repo illustrations" : ", text only (ORV_BITTU_ILLUSTRATIONS=0)"
    }…`,
  );

  const parsed: { num: number; title: string; body: string }[] = [];

  for (let i = 1; i <= limit; i++) {
    const url = chapterUrl(i);
    const res = await fetch(url, {
      headers: { "User-Agent": "orv-reader-ingest/1.0" },
    });
    if (!res.ok) {
      console.warn(`  HTTP ${res.status} for ${url} — stopping.`);
      break;
    }
    const raw = await res.text();
    const ch = parseChapterFile(i, raw, useIll);
    if (ch) parsed.push(ch);
    if (i < limit) await sleep(delay);
    if (i % 50 === 0) console.log(`  … ${i}/${limit}`);
  }

  if (parsed.length === 0) {
    console.error("No chapters imported.");
    process.exit(1);
  }

  console.log(`Parsed ${parsed.length} chapter(s). Writing database…`);
  await writeNovelChaptersToDb(prisma, PROJECT_ROOT, parsed);
  console.log("Done. Open /chapters — source: github.com/Bittu5134/ORV-Reader");
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
